### ISSUE TITLE
Choice element toevoegen voor indiener

### ISSUE THREAD

**Issue by lmasrarsaml** [lmasrarsaml/ORI-XSD#14]
Indiener heeft nu twee elementen die verwijzen naar andere elementen: `isNatuurlijkPersoon` en `isOrganisatorischeEenheid`. Gezien het informatiemodel stelt dat dit een keuze is, is dit op te lossen door `choice` elementen toe te voegen.

**Comment by rien333** [comment]
Je oplossing werkte helaas niet.

**Comment by lmasrarsaml** [comment]
Oplossing aangepast, zo zou het moeten werken.

choice elementen opgemaakt voor het nieuwe attribuut 'isEntiteit' en deze gevuld met isNatuurlijkPersoon en isOrganisatorischeEenheid.
