### ISSUE TITLE
`xsd:ID` kan niet beginnen met een cijfer

### ISSUE THREAD

**Issue by rien333** [lmasrarsaml/ORI-XSD#4]
`<ID>` tags verwachten nu als waarde `xsd:ID`. Dit levert in de praktijk echter problemen op, omdat deze waarde geen strings toestaat [die beginnen met een cijfer](http://www.datypic.com/sc/xsd/t-xsd_ID.html). 

Aangezien IDs in de praktijk wel vaak met cijfers beginnen moeten het bereik van `<ID>` elementen anders gedefinieerd worden.

**Comment by lmasrarsaml** [comment]
Opgelost door het datatype van ID aan te passen naar string.
